### ISSUE TITLE
Подключение тестового бэка к gdmn-nlp-demo

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#101]
- [x] В store хранить параметры подключения. Сделать отдельный экран, для их вывода/изменения. Там же кнопка **Загрузить ER Model**. Изначально модель грузится из файла, как сейчас и сделано. Если есть тестовый бэк, то модель можно загрузить с него.
- [x] На экране **Syntax**, рядом с кнопкой Analyze, добавляем кнопку **Query** (если введены параметры подключения к тестовому бэку). По нажатию на эту кнопку, если фраза разобрана и без ошибок превращена в команду, то команда отсылается на тестовый бэк. Результат выполнения загружается в виде **RecordSet** в store.
- [x] Если в store присутствует **RecordSet** с данными (результат выполнения команды на тестовом бэке). То появляется в меню команда **RecordSet** по которой открывается экран с гридом, где выводятся данные.

**Comment by sywka** [comment]
#95
