### ISSUE TITLE
Инкрементная подгрузка

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#102]
1. На клиенте инициируется процесс получения данных. Например, пользователь нажал кнопку показать данные для некоторой сущности из ERModel.
2. Формируется Query и передается на сервер для выполнения. При этом клиент может сообщить сколько строк данных он хочет получить. Если не указано, то вступает в силу некоторое разумное значение по-умолчанию, зашитое в бэк. Например, 40-50 записей будет достаточно.
3. Сервер выполняет запрос и фетчит внутрь себя заданное количество данных. И смотрит, они там еще есть или все -- дошли до конца выборки.
4. Сервер шлет ответ на клиента. Успешный ответ бывает двух типов: первая порция данных, есть еще. Или данные и все -- больше нет, выборка закончилась.
5. Получив данные клиент создает RecordSet, заполняет его и диспатчит в сторадж. Интерфейс пользователя перерисовывается. Рисуется грид, исчезает надпись Loading...
6. В зависимости от того, какой пришел ответ: это все данные или только их часть, в RecordSet выставляется соответствующий флаг. Что-то типа `srcEOF: boolean`.
7. Когда GDMNGrid пытается залезть за конец данных (или пользователь курсор перемещает за последнюю запись, или прокрутку делает), то система смотрит на флаг в RecordSet. Если еще не достигнут конец данных, то на сервер отсылается команда за следующей порцией. Обратите внимание, что ее размер надо грамотно рассчитать это не должно быть слишком маленькое число, так как если мы будем дергать записи по одной, то затормозим все. И слишком много не должно быть -- иначе фронт зависнет. Т.е. в идеале это число зависит от того, что там произошло в гриде, но ограничено и сверху и снизу.
8. Ответ сервера опять-таки двух типов: это уже все данные или данные и еще что-то осталось на сервере. В зависимости от него выставляется флаг в RecordSet.
9. Мы используем **ТОЛЬКО** наш RecordSet и наш GDMNGrid. Не надо лезть в дебри **react-virtualized** забудьте про него, как буд-то его просто нет.

**Comment by sywka** [comment]
Задача Query с флагом sequentially это и есть рекорд сет, идентификатором которого является taskKey. Она не завершается пока на сервере жив рекордсет и является своеобразной меткой для запросов данных FetchQuery. Задача Query может завершиться сама, при полном прочтении рекорд сета (Success), может быть прервана клиентом (Inerrupted), например пользователь закрыл грид, или завершится с ошибкой создания statement (Error). Эта задача является управляемой, не должна ничего возвращать и должна отображаться в списке долгих выполняемых задач. Получение данных выполняется командой FetchQuery в которую передаётся необходимое число строк. При успешном завершении этой команды возвращается результат (Success). В случае ошибки - ошибка (Error). Мешать логику получения данных и создания statement считаю неправильным. Это абсолютно разные вещи со своим поведением и ошибками.

**Comment by gsbelarus** [comment]
Вот смотрите, почему я считал задачу очень легкой и не понимаю, куда мы тратим время. В гриде есть такой код:
```ts
          case 'ArrowDown':
            if (currentRow < rowCount - 1) {
              newRow = currentRow + 1;
            }
            break;
```
Он обрабатывает нажатие стрелки вниз. Я планировал добавить в него несколько строк:
```ts
          case 'ArrowDown':
            if (currentRow < rowCount - 1) {
              newRow = currentRow + 1;
            } else {
              if (!rs.srcEOF) {
                const { onLoadMoreData } = this.props;
                const deltaRows = Math.ceil(bodyHeight / rowHeight);
                onLoadMoreData(deltaRows);
              }
            }
            break;
```
`onLoadMoreData` -- ивент, который мы добавим в gdmnGrid. 

Единственная здесь тонкость -- так как мы не двигаем курсор сразу, то надо где-то запомнить дельту, на которую должен сдвинуться курсор (в данном случае +1) и при подгрузке порции данных -- передвинуть курсор.

**Comment by gsbelarus** [comment]
A K:
у нас есть архитектура: 1) реакт роутер создает data view 2) data view обнаруживает, что нeт rs. это значит режим загрузки. не рендерятся гриды, а рендерится Лоадинг... 3) data view вызывает event загрузки данных 4) ивент формирует query и шлет на сервер 5) сервер присылает ответ. первая порция 80-100 записей. число закодировано константой. 6) на основе ответа создается recordset и размешается в store 7) происходит ре рендер формы. теперь есть данные и уже рендерится грид. 8) по мере скролинга грид подгружает новые порции данных ориентируясь на флаг rsEOF в recordset.

**Comment by sywka** [comment]
Можно закрывать?
