### ISSUE TITLE
ScrollIntoView теперь не работает

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#110]
Похоже с последними изменениями с ref в гриде перестал работать ScrollIntoView. Собственно, ради него (т.е. прокрутки грида, чтобы курсор становился видимым на экране) этот ref и передавался везде.

![image](https://user-images.githubusercontent.com/5175764/53978297-eeede000-411b-11e9-8307-b1a7c3d33c4e.png)

**Comment by gsbelarus** [comment]
![image](https://user-images.githubusercontent.com/5175764/53978654-cd412880-411c-11e9-9f6d-66293831d5f4.png)

**Comment by gsbelarus** [comment]
В общем, похоже это не тот объект. Т.е. надо всё таки ref брать, а не this.

**Comment by gsbelarus** [comment]
блин, вот нет у нас тестирование на грид, а там все посыпалось... что раньше работало.

1. scrollIntoView теперь не работает
2. соответственно теперь некорректно работает режим поиска. Т.е. он ищет себе там, но по кнопка перехода между найденными не переходит.
3. неправильно терерь работает окно сортировки. не сохраняет позицию курсора.
4. соответственно, неправильно работает и сортировка по клику на заголовок колонки...

надо все вернуть как было.

**Comment by sywka** [comment]
Ошибка из колбэков GDMNPanel. Я ее не трогал, там по прежнему берется ref, только судя по всему не Grid-а, а его container-а. Т.е есть вероятность, что оно и не работало, до последних изменений.

ref это и есть тот же this, просто доступ к нему открывается когда компонент выполнил render.
В нашем случае callback-и вызываются после вызова render компонента, а значит можем смело передавать this.

**Comment by sywka** [comment]
[Breaking change](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0) в react-redux
