### ISSUE TITLE
Копирование баз

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#123]
Должно быть так:

1. На сервере в выделенной папке набор эталонных баз. (Например, голый эталон, только с таблицами. База комплексной автоматизации. База торговли и т.п.).
2. К ним JSON файл где в массиве хранится имя эталонной БД и ее описание.
3. Пользователь подключается и может выбрать на основе какой БД сделать себе базу.
4. Эталон копируется в папку этого пользователя.
5. Базе пользователя присваивается новый DBID. Это у нас случайное положительное целое число в диапазоне 2000 < DBID <= MAX_INT_32.
5. В системной БД прописывается информация о ее регистрации и т.п.

**Comment by sywka** [comment]
только в пункте 5 у нас используется не id из бд, а строковый UUID

**Comment by gsbelarus** [comment]
тут имеется ввиду присвоить новое значение генератору gd_g_dbid
