### ISSUE TITLE
Поддержка простых и интервальных деревьев

### ISSUE THREAD

**Issue by sywka** [gsbelarus/gdmn#13]
Для этого у `Entity` должны быть типы:
* обычное entity
* простое дерево
* интервальное дерево

Так же поддержку деревьев нужно добавить в **gdmn-er-bridge**. 
* сериализация `ERModel` в физическую структуру БД и обратно
* чтение данных

**Comment by IharOknorp** [comment]
Реализовано и оттестировано тестами:
1 Простое дерево. Добавление в Entity булевского свойства: IsTree.
Проверочный тест : packages - gdmn-er-bridge - test - query.test.ts -  Название теста - "simple tree"

2  Интервальное дерево.  Добавление в Entity атррибутов "RB" и "LB"
Проверочный тест : packages - gdmn-er-bridge - test - query.test.ts - Название теста -   "ParentAttribute: inheritance: ParentAttribute, HasRoot parentRelationFields"
