### ISSUE TITLE
Неправильный логин или пароль при регистрации внешней БД

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#157]
Если при регистрации внешней БД указать неверный логин или пароль, то система повисит-повисит и вернет список баз данных в исходное состояние при этом никаких сообщений не будет ни на экране, ни в логе. А должно сказать что-то понятное пользователю.

**Comment by gsbelarus** [comment]
То есть сейчас рассматриваем два варианта:

1. Сначала отдельно подключаемся к БД без пула. Если ошибка, то вы водим ее в лог и передаем на клиента. Если успех, то отключаемся и подключаемся уже через пул. Выглядит конечно не очень профессионально. Как затычка какая-то.
2. Сделать форк библиотеки пула и подправить там все, что нам надо. Отправить PR автору. Пока он не подправит -- использовать наш форк. Выглядит уже получше.

**Comment by gsbelarus** [comment]
И, как я понял, еще и на клиенте что-то придется допиливать, чтобы ловились ошибки правильно.

**Comment by sywka** [comment]
По поводу пункта 2 - уже есть PR, но без апрува https://github.com/coopernurse/node-pool/pull/184

**Comment by gsbelarus** [comment]
Судя по датам там этот PR никогда не будет смержен. Надо делать свой форк и подправить или вообще выкинуть эту библиотеку. Она у нас только для конектов к БД используется?

**Comment by sywka** [comment]
Скорее всего да, не будут его мержить). Кроме драйвера эта либа используется для реализации пула дочерних процессов.

В идеале, конечно нужно доделать либу пулов, но сейчас мне кажется нет смысла тратить силы на совершенствование своего пула, если с выходом Firebird 4, его скорее всего заменит встроенный. Чисто для процессов разве что.

Самый оптимальный вариант, как мне кажется, сделать затычку (1 пункт)
Добавить в [ADatabase](https://github.com/gsbelarus/gdmn/blob/master/src/gdmn-back/src/apps/base/ADatabase.ts) метод:
```ts
public async ping(): Promise<void> {
  const {driver, connectionOptions} = this.dbDetail;
  const testConnection = driver.newConnection();

  try {
    await testConnection.connect(connectionOptions);
  } finally {
    if (testConnection.connected) {
      await testConnection.disconnect();
    }
  }
}
```
и внутри реализации команды CREATE_APP вызывать.

По сути мы это же делаем только с пулом соединений. Только там у нас идет полная инициализация приложения, а с этим методом мы ограничимся только коннектом к БД. Будет быстрее

**Comment by ilonaand** [comment]
Уже написали метод, показывает ошибку правильно выдает

**Comment by sywka** [comment]
А вообще повторюсь, основная проблема в драйвере, т.к при большом количестве реконнектов ( в следствии особенности работы пула), драйвер кладет весь процесс с каким-то кодом

**Comment by gsbelarus** [comment]
Т.е. если написать маленький тестик на голом драйвере, который просто в
цикле будет пытаться много раз подключиться к существующей БД с неверным
логином/паролем, то драйвер упадет?

Илона, надо написать -- отправим фернандесу пусть исправляет.

**Comment by sywka** [comment]
Я думаю да, но нужно проверить. Заодно посмотреть с каким кодом процесс завершается на windows

**Comment by IharOknorp** [comment]
Сообщение выводится:
 Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
