### ISSUE TITLE
GD_DOCUMENT.TRTYPEKEY: no entities for table GD_LISTTRTYPE

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#158]
При подключении бэком к нашей бух базе такая красота в логах. Надо разобраться почему GD_LISTTRTYPE не распознает как Entity.

Внимание! Создать себе копию бд и с ней работать. Ни в коем случае не эксперементировать на нашей рабочей БД.

**Comment by ilonaand** [comment]
GD_LISTTRTYPE это старые типовые операции, они есть на нашей базе и на березе. Это не Entity
