### ISSUE TITLE
Фронт не подключается к бэку

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#19]
1. если в бэке где-то зарегистрирована база и он не может ее найти, то все -- бэк падает и фронт не может подключиться вообще. Это в корне не правильно. Баз может быть много. Вот например мой рабочий список:

![image](https://user-images.githubusercontent.com/5175764/44907402-7ba88300-ad20-11e8-8f62-e02d2b505f69.png)

И если из-за одной отсутствующей все будет падать, то я вообще никогда на подключусь к Гедымину.

2. Хранить список баз в базе MAIN.FDB плохая идея. 

Во-первых, какая структура этой бд? В Гедымине у нас есть SQL файлы, а тут все зашито в код? 

Во-вторых, ее структуру со временем тоже придется апгрейдить и это лишняя головная боль на ровном месте. 

В-третьих, чтобы влезть в нее понадобится сторонняя (и платная) утилита IBExpert. И я даже не знаю, существуют ли какие либо утилиты под Mac или Linux. 

В-четвертых, как переносить информацию из базы в базу, как объединять? А это обязательно понадобится разработчикам у каждого из которых может быть свой локальный сервер баз данных и свой gdmn-back.

В-пятых, понадобится сервер для доступа к этой базе, который может конфликтовать с основным сервером баз данных предприятия, или, даже если не будет конфликтовать, то мы будем подключаться под учетной записью, пароль которой будет где, у нас в коде прописан?

3. Надо использовать JSON файл для этих целей, который снимает все вышеуказанные проблемы.

4. И, перед тем как переделывать, написать и обсудить TODO, чтобы потом в третий раз не пришлось переделывать.

**Comment by sywka** [comment]
По поводу первого пункта - решено. Теперь "подключение" к базе данных (чтение структуры БД, создание пула соединений и ERModel) происходит при подключении первого пользователя. Это значит, что если БД недоступна или в процессе возникнет ошибка, она обработается и уйдет только этому пользователю.

Касательно остального, все-таки предлагаю оставить MAIN.DB и со временем доделать до нужного состояния. Тогда в будущем будет возможность общаться с ней по тому же протоколу, что и с другими базами, точнее это можно делать уже сейчас (подключиться, получить ERModel, выполнить какие-либо команды)

**Comment by sywka** [comment]
Можно закрывать?
