### ISSUE TITLE
Анализ и выбор инструмента сохранения пользовательских настроек

### ISSUE THREAD

**Issue by IharOknorp** [gsbelarus/gdmn#195]
**Client**
Проведя анализ на стороне клиенте можно выделить основные инструменты и их основные плюсы и недостатки: 
_1.  IndexedDB API_ - низкоуровневое API для клиентского хранилища большого объема структурированных  данных.
+ асинхронное использование
+ работать вне сети
+ хранилище ключ-значение быстрое
- слишком сложный для простых задач
- не поддерживаются всеми основными браузерами
- данные хранятся на стороне клиента
- данные только по конкретному пользователю

_2.  localForage_  - не localStorage
+ асинхронное использование
+ работать вне сети
+ предлагает API обратного вызова, а также поддержку ES6 Promises API 
+ поддержка блобов
+ просто в использовании
- данные хранятся на стороне клиента
- данные только по конкретному пользователю

_3.  Куки_

- множество проблем с безопасностью
- неспособны хранить сложные данные
- устаревшая технология

_4.  Cache_ 

+  Cache обычно используется в сочетании с Service Worker API,
- плохая поддержка браузеров
- экспериментальный проект

**Server**
Проведя анализ на стороне сервера можно выделить основные инструменты и их основные плюсы и недостатки: 
_1. firebird_

+ данные хранятся в основной БД
+ самый надёжный и долгосрочный способ хранения данных.
+ можно работать с данными всех пользователей для составления отчетов и т.п
+ уже написаны собственные инструменты для работы с БД.
- увеличивается основная БД

_2. NoSQL_ 

+ можно работать с данными всех пользователей для составления отчетов и т.п
+ хранилище ключ-значение быстрое
- Приходится разрабатывать собственные инструменты для работы с БД.
- Слабые ACID свойства (отсутствует поддержка транзакций )

_3. Запись и последующее хранения файла на сервере в формате JSON_

+ Не делает нагрузку на основную БД
- Права доступа для записи все пользователям системы

**Comment by IharOknorp** [comment]
Структура таблицы GD_STORAGE_DATA.
 GUID         | VERSION |  JSON
1234-3333    v.1             {"hiiden": "false"}

Структура таблицы соответствия по юзеру 
USERID | GUID        | VERSION
51	      1234-3333   v.1

Если юзер заходит у него будет два варианта для работы с шаблоном.
1. Отредактировать форму и сохранить
2. На форме размешаем кнопку выбора шаблона. Где пользователь может из GD_STORAGE_DATA по GUID выбрать любой понравившийся шаблон.

На форме GD_STORAGE_DATA размещаем кнопки "Выгрузка шаблонов", "Загрузка шаблонов" где можно выгрузить/ загрузить ранее созданные шаблоны

**Comment by IharOknorp** [comment]
еще автоматический вариант если базу с вышеописанной структурой разместить на одном сервере а последующие базы имели бы возможность подключатся к ней и работать с этими данными

**Comment by IharOknorp** [comment]
1.  таблица соответствия Entity - GUID

EntityName | GUID 
данная таблица нужна т.к entity создается каждый раз когда происходит подключение к бД и будет каждый раз новый GUID.
В случае если происходит изменение в названии Entity то следует внести изменения и в название Entity  в соответствующей строке физической таблицы
В случае если происходит удаление Entity то следует удалить данные в соответствующей строке физической таблицы
В случае если происходит добавление Entity то следует добавить новые  данные в соответствующей строке физической таблицы
 
2. Открытие формы

Для работы данной формы нужна таблица Property Tinctures со след. структурой
GUID | VERSION| TYPE | TYPEVALUE

При открытии формы требуется сразу сделать проверку если  такой GUID в  таблице соответствия Entity - GUID.
Если нет то сразу устанавливаем настройки для формы по умолчанию
Если же найден то делаем проверку по type "USER" и его ID, если true - применяем настройки, если false - делаем поиск по type "Group" если true то применяем настройки, если же нет то делаем поиск по по type "company ".  если true то применяем настройки, если же нет тогда делаем проверку доступен ли нам глКаталог если же да тогда в нем ищем по GUID и если находим применяем настройки если нет то тогда открываем форму с дефолтными настройками.

3. Закрытие формы 

При закрытии формы делаем поиск GUID  в  таблице соответствия Entity - GUID если к примеру это была форма создания нового Entity его в  таблице соответствия Entity - GUID не будет и нам требуется его записать. В не зависимости нашли мы его или нет нам требуется сделать проверку были ли на данной форме какие либо изменения если нет то можно закрыть форму если же были тогда сделать проверку какие права у данного пользователя.
Если же обычный юзер то программно делается запись в таблицу  Property Tinctures
с type USER и в TYPEVALUE указывается его ID
если же юзер с правами для группы то   делается запись в таблицу  Property Tinctures
с type GROUP и в TYPEVALUE  указывается его группа
если же юзер с правами для организации то   делается запись в таблицу  Property Tinctures
с type COMPANY и в TYPEVALUE  указывается его компания
далее требуется проверка установлен ли флаг Public  если он не стоит то форма закрывается если же стоит тогда сделать проверку если ли у нас доступ к удаленному каталогу. Если есть то сохраняем туда JSON файл если же нет тогда вывести сообщение - ошибку

Структура таблицы GD_STORAGE_DATA.
GUID | VERSION | JSON

**Comment by gsbelarus** [comment]
Тз тут:

https://github.com/gsbelarus/gdmn/blob/master/docs/TODO/todo0022.settings.md

Порядок реализации я бы определил такой:

1. Делаем функции на клиенте для поиска, сохранения, удаления. Эти функции для начала работают только с локальным хранилищем и не трогают серверную часть, т.е. работают как сейчас. Подключаем их в код для грида и дизайнера.

2. Делаем заглушки (пустые функции) на стороне сервера и реализуем сетевой протокол. Т.е. никаких файлов, никакого поиска настроек. Просто -- получили по сети запрос -- вернули ответ как буд-то ничего не найдено. Подключаем работу по сети в клиентский механизм.

3. Реализуем работу с файлами и объектами на стороне сервера. Поиск, добавление, изменение, удаление настроек.

4. В последнюю очередь реализуем media query и прочие неприоритетные вещи.

**Comment by IharOknorp** [comment]
реализован п.2. 
К примеру: 
apiService.querySetting({params: [{type: 'string', objectID: '51'}]})

**Comment by gsbelarus** [comment]
Ответы на некоторые вопросы:

## Что такое приложение?

Например, возьмем базу Березовского мясокомбината. Там есть **приложения**: Зарплата и Кадры, Общепит, Материальный склад. Общепиту надо в товаре видеть кучу показателей (белки, жиры, углеводы, калорийность), которые не нужны Матскладу. Отдел кадров использует кучу своих полей в справочнике сотрудников, которые не нужны Общепиту и т.п.

Хотелось бы иметь возможность настраивать окна, гриды под специфику каждого приложения. Сейчас, в Гедымине, эта проблема никак не решается. Гриды все равно **целиком** хранятся для каждого пользователя, т.е. каждый пользователь настраивает под себя и не пересекается больше ни с кем. А в диалоговых окнах просто раскидывают управляющие элементы по разным вкладкам.

## Какие настройки можно собирать инкрементно, а какие нет

Настройки грида можно собирать из разных объектов. Грид с накладными настроен в объекте для конкретно этого объекта. Затем, некоторый пользователь скрывает в нем несколько колонок, которые лично ему не нужны на экране. Получатся два объекта: исходный со всеми настройками и объект данного пользователя, что-то вроде:
```
{
  column1: {
    hidden: true
  },
  column2: {
    hidden: true
  }
}
```

Настройки диалогового окна скорее всего **нельзя** собирать из разных кусочков. Т.е. они должны храниться целиком, единым объектом.

## Как мы будем сейчас создавать настройки под пользователя, группу, приложение и т.п.?

На первом этапе никак. У нас настройки хранятся на сервере в файлах. Простых текстовых файлах в JSON формате. Мы зайдем в Notepad++ и наделаем этих копий сколько угодно,
поменяв или присвоив значения нужным нам полям.

**Comment by gsbelarus** [comment]
@LenaBuraja @ilonaand у нас пока очень простая задача в два действия -- прочитать весь файл за раз и распарсить в JS объект. и два действия в обратную сторону. есть ли смысл тянуть отдельную библиотеку? я бы пока сделал без неё.
