### ISSUE TITLE
Почему бы DDLHelper-у самому не управляться с AT_ таблицами

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#20]
К чему лишний код?

```ts
      await this._getDDLHelper().addColumns(tableName, [{name: fieldName, domain: domainName}]);
      await this._insertATAttr(attr, {relationName: tableName, fieldName, domainName});
```

**Comment by sywka** [comment]
Теперь добавление информации в **AT...** таблицы происходит в методах **DDLHelper**. Однако это работает только для основной информации вроде имен таблиц, полей и тд. Всю дополнительную информации, в том числе информацию, требующуюся для функционирования новой платформы, нужно добавлять через методы `ddlHelper.cachedStatements.updateAT...`. 

Думаю на этом можно закрывать issue.
