### ISSUE TITLE
Повторный вызов процедуры апгрейда

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#21]
Я еще не залазил в код, просто спрошу. Сделанный алгоритм устойчив к повторному вызову. Например, в Гедымине я периодически проверяю -- очищаю таблицу с информацией о версиях БД и за пускаю программу. Все процедуры проходят заново и не должно быть ошибок. Т.е. каждый код сначала проверяет, может уже такие объекты есть, и только потом выполняет заданные действия по апгрейду.

**Comment by sywka** [comment]
Решено в [7677ab6](https://github.com/gsbelarus/gdmn/commit/7677ab6)
