### ISSUE TITLE
Не удается подключить внешнюю базу

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#246]
Пытаюсь подключить внешнюю базу:

![image](https://user-images.githubusercontent.com/5175764/67955301-6e787400-fc03-11e9-8357-802d6224de6a.png)

Получаю сообщение об ошибке, что-то связанное с template.

После этого уже нельзя вылогиниться и залогиниться по новой. Будет сообщение:

> Subscriptions with same destination exists, Subscriptions with same destination exists

**Comment by gsbelarus** [comment]
похоже, что там первичое -- это ошибка с шаблонами баз данных. надо подумать, если база перечислена в templates.json но ее нет в папке, то может не стоит кидать ошибку, а игнорировать подобную ситуацию с записью предупреждения в лог.

и в вышеуказанном окошке следует Username заменить на Firebird user. Чтобы человек не сомневался какой логин ему вводить.

**Comment by stasgm** [comment]
Если идёт подключение к базе не FB 3 (или, хайли лайкли, другая ошибка подключения), то сервер бесконечно пытается подключиться получает ошибку и снова пытается подключится, соответственно фронт ждёт ответа.
![image](https://user-images.githubusercontent.com/8355925/68084578-72490800-fe48-11e9-8f6c-5f799e3b54f7.png)

**Comment by stasgm** [comment]
Последняя проблема не актуальна. В дев. конфиге прописана 1 минута ожидания. Я не ждал так долго и решил, что идёт бесконечная попытка подключения.

https://github.com/gsbelarus/gdmn/blob/master/src/gdmn-back/config/development.json#L58
