### ISSUE TITLE
Избавиться от exported enum const

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#28]
Вопрос в оптимальности. Надо посмотреть, что придумало Microsoft в fabric-ui, как и на что они заменили глобальные enum.

* [ ] gdmn-nlp
* [ ] gdmn-orm
* [ ] gdmn-nlp-agent
* [ ] gdmn-er-bridge
* [ ] gdmn-db
* [ ] gdmn-recordset
* [ ] gdmn-grid
* [ ] gdmn-back
* [ ] gdmn-front

Единственное, что чуть-чуть можно подождать до очередной версии TS. Возможно, что они как-то решат эту проблему на уровне компилятора.

**Comment by punkusha** [comment]
@gsbelarus как воспроизвести ошибку?

**Comment by gsbelarus** [comment]
пока ничего НЕ ТРОГАЕМ! будем еще выяснять.
