### ISSUE TITLE
Подключение по локальному протоколу и со встроенным сервером

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#34]
1. У ФБ есть режим локального подключения, когда вызывающий процесс и сам сервер физически выполняются на одной машине. В этом случае не указывается имя сервера и номер порта. Локальное подключение быстрее так как не задействуется TCP/IP стек, а процессы общаются между собой другими средствами.

2. Посмотреть возможность подключения через встроенный сервер (embedded). В этом случае отдельный процесс сервера ФБ вообще не запускается.

**Comment by sywka** [comment]
Такая возможность есть в нативном драйвере, просто для упрощения и "однотипности" подключения для всех будущих драйверов для gdmn-db добавил только один способ коннекта - по TCP. Если есть необходимость, могу добавить.

**Comment by sywka** [comment]
Опции для соединения с бд теперь выглядят так:
```ts
export interface IConnectionServer {
    host: string;
    port: number;
}
export interface IConnectionOptions {
    server?: IConnectionServer;
    username: string;
    password: string;
    path: string;
}
```
Нужно обновить все файлы конфигурации в соответствии с новыми шаблонами.
