### ISSUE TITLE
протоколы и не только...

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#4]
1. когда я говорю STOMP или AMQP, то имею ввиду *исключительно* формат сообщения и не большею. Ни порядок обмена сообщениями, ни промежуточные программы-брокеры я не рассматриваю.

Конечно, мы можем составить полностью свой формат. Например, сообщение будет выглядеть как JSON объект такой структуры:
```ts
{
  version: "1.0",
  messageType: "data-packet",
  messageBody: {
    recordSet: [
      {record1},
      {record2},
      ...
      {recordN}
    ]
  }
}
```
Но, почему бы не придерживаться одного из известных форматов? Вреда не будет, а польза может и появиться со временем. Это как пространства имен в Гедымине в формате YAML. Мы нигде, никогда не использовали никакой сторонней программы, которая бы что-то делала с нашими ПИ и требовала формата YAML. Т.е. мы вполне могли изобрести свой личный формат.

2. Транспорт. Это протокол низового уровня, который будет передавать наши сообщения. Он ничего не знает о нашей бизнес-логике и умеет только работать с сетью. Для этих целей мы будем использовать готовые решения/библиотеки. Например, WebSocket, HTTP, HTTP2 и т.п.

3. Клиент -- программа работающая в браузере или на мобильном устройстве. Наш проект gdmn-front.

4. Сервер -- программа, облуживающая запросы от клиента. Наш проект gdmn-back.

5. Обмен данными и командами между клиентом и сервером осуществляется **ТОЛЬКО** посредством посылки-приема сообщений.

6. Очередь сообщений это массив JavaScript или объект, включающий в себя такой массив. Сообщения помещаются в массив, после чего механизм пересылки начинает их передачу на сервер. Если в данный момент времени нет соединения, то механизм ждет, пока оно появится. Насколько это возможно, клиент продолжает работу даже если в очереди есть неотосланные сообщения.

7. На сервере тоже ведется очередь сообщений, куда сетевой механизм помещает принятые сообщения, и откуда механизм выполнения берет информацию чем ему заниматься. При пересылке сообщения на клиента тоже может возникнуть ситуация, когда соединение отсутствует. В этом случае сетевой механизм сервера ждет и пересылает сообщение позже.

8. Протокол -- это набор правил, регламентирующих порядок обмена сообщениями. Например:

> Сообщение, помещенное в очередь получает статус ready-to-send.
> 
> Сообщение переданное на сервер и помещенное в очередь для обработки получает статус in-queue.
> 
> Сообщение полученное с сервера получает статус recieved.

Выше -- это только пример. Сам протокол и надо сейчас разработать, задокументировать и проиллюстрировать схемами.

9. Наша система не построена по принципу **микросервисов**. По крайней мере пока. Я не вижу как обойти последовательность DB Connection -> Session -> Query -> Transaction -> SQL -> Result. Другими словами, все равно все сведется к тому, что у нас **одна** база данных и команды **должны** выполняться в рамках конекта-транзакци к этой базе данных.

Возможно, в будущем, мы придем к системе, где будет использоваться несколько баз данных. Тогда сообщения можно рассылать нескольким серверам и тут нам может понадобится отдельный, внешний брокер и т.п. Именно по этому я и говорю, что по возможности мы должны следовать стандартам в формате сообщения. И, возможно, реализовывать наш протокол максимально близко к неким существующим протоколам.

**Comment by sywka** [comment]
На данный момент выбрали:
 * Формат сообщений - [STOMP](https://stomp.github.io/stomp-specification-1.2.html)
 * Транспорт на стороне сервера - [WebSocket](https://github.com/websockets/ws)
 * Для общения по протоколу **STOMP** на сервере [node-stomp-protocol](https://github.com/pcan/node-stomp-protocol)
 * Транспорт на стороне клиента - нативный **WebSocket**
 * Для общения по протоколу **STOMP** на клиенте [webstomp-client](https://github.com/JSteunou/webstomp-client)

Используемые библиотеки **STOMP** являются реализацией спецификации (скорее всего не полной) и не более того. Вся логика общения, работа с очередью и тд. реализуются отдельно в **gdmn-back** и **gdmn-front**

**Comment by punkusha** [comment]
STOMP прост в реализации, думаю, лучше написать самим - либы очень слабые и с багами
