### ISSUE TITLE
Вопрос по устройству кода gdmn-front

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#42]
Не совсем понятно в чем смысл использовать рекомпозе код, а не просто внутри компонента прописать didmount, willunmount?

![image](https://user-images.githubusercontent.com/5175764/49223666-6959e600-f3f0-11e8-9c1f-25f44b2c3e7e.png)

**Comment by punkusha** [comment]
чтобы компонент оставался максимально тупым и для разделения ответственности. хендлеры для ui actions это его уровень, а вот подготовка клиента для работы с api - нет, это как раз задача для контейнера

**Comment by gsbelarus** [comment]
уже с лета принято, что концепция"тупых" компонентов так себе... и пришел к этому выводу сам автор ))

![image](https://user-images.githubusercontent.com/5175764/49224510-a626dc80-f3f2-11e8-942f-660191ebe137.png)
