### ISSUE TITLE
Диаграмма состояний и диаграмма последовательности

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#45]
Надо сесть и аккуратно написать диаграмму состояний для клиентской и серверной частей и диаграмму последовательности. Пока наш протокол еще не стал слишком сложным. 

Можно просто текстом сделать. Я сам оформлю как надо.

**Comment by sywka** [comment]
Краткая информация о работе протокола и структуре серверной части находится [здесь](https://github.com/gsbelarus/gdmn-back/wiki/STOMP). Чуть позже перенесу в **gdmn**, если потребуется.

**Comment by stasgm** [comment]
Марина хлопнула дверью)

**Comment by punkusha** [comment]
> Марина хлопнула дверью)

@stasgm ошиблась дверью)
