### ISSUE TITLE
gdmn-front не запускается

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#52]
yarn build проходит, а вот yarn start -- нет.

> ERROR in ./src/app/index.tsx
> Module build failed (from C:/Golden/NS/gdmn/node_modules/react-hot-loader/webpack.js):
> TypeError: Cannot read property 'indexOf' of undefined
>     at transform (C:\Golden\NS\gdmn\node_modules\react-hot-loader\dist\webpack.development.js:70:14)
>     at Object.transform$1 (C:\Golden\NS\gdmn\node_modules\react-hot-loader\dist\webpack.development.js:107:14)
>  @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry.js (webpack)-dev-server/client?http://localhost:9090 (webpack)/hot/dev-server.js ./src/app/index.tsx app[3]
> i ｢wdm｣: Failed to compile.
> × ｢atl｣: Child process failed to process the request: Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.

**Comment by punkusha** [comment]
для корректного теста проделайте следующее

1) тест build

в **gdmn**:
```bash
yarn run clean
```
 в **gdmn-front**:
```bash
yarn run yarn:reinstall
yarn run build
```
2) тест start

в **gdmn**:
```bash
yarn run clean
```
в **gdmn-front**:
```bash
yarn run yarn:reinstall
yarn run pkg-links:build
yarn run start
```

**Comment by punkusha** [comment]
думаю пришло время подключить для этого ci, чтобы не было вопросов

**Comment by gsbelarus** [comment]
yarn build из корня работает. но, оно затрагивает и фронт и демо проекты. а это всё билдится очень долгою мне бы иметь возможность одной командой еребилдить только библиотеки. не трогая папку /src.
