### ISSUE TITLE
Некорректное чтение чисел с плавающей запятой

### ISSUE THREAD

**Issue by sywka** [gsbelarus/gdmn#55]
Записав одно значение (930687.8979) в поле с типом FLOAT после чтения получаем другое (930687.875).
Нужно разобраться в чем проблема и исправить

**Comment by gsbelarus** [comment]
FLOAT столько значащих цифр хранит. Не надо его использовать. Надо использовать DOUBLE PRECISION.

**Comment by sywka** [comment]
А можно подробнее про float в fb. Мне казалось там просто диапазон меньше чем в double, почему после запятой идут некорректные значения?

Если есть какие-то ограничения возможно лучше их добавить и в драйвер, чтобы избежать появления в runtime?

**Comment by gsbelarus** [comment]
> For testing data in columns with floating-point data types, expressions should check using a range, for instance, BETWEEN, rather than searching for exact matches.

https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-datatypes-floattypes.html

> FLOAT
> 
> This data type has an approximate precision of 7 digits after the decimal point. To ensure the safety of storage, rely on 6 digits.
> 
> DOUBLE PRECISION
> 
> This data type is stored with an approximate precision of 15 digits.

**Comment by gsbelarus** [comment]
Мы сами должны использовать только DOUBLE PRECISION. На уровне нашей платфомы даже не будет возможности создать поле с плавающей точкой другого типа.

**Comment by gsbelarus** [comment]
> А можно подробнее про float в fb. Мне казалось там просто диапазон меньше чем в double, почему после запятой идут некорректные значения?

в двух словах:

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by sywka** [comment]
По итогу просто не используем этот тип у нас в проекте, а в драйвере оставляем все как есть.
Можно закрывать?
