### ISSUE TITLE
Некоторые вопросы по моно-репозиторию и lerna

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#6]
Насколько я понимаю, структура исходников будет следующая:

````
\
  \packages
    \gdmn-db
      \dist
      \node_modules
      \src
        ...
    \gdmn-orm
      \dist
      \node_modules
      \src
        ...
  \src
    \gdmn-front
      ...
    \gdmn-back
      ...
````

Если не так, поправьте меня.

### Одна наша библиотека использует другую

Предположим, что **gdmn-orm** использует **gdmn-db**. Т.е. содержит операторы `import { something } from 'gdmn-db';` Что именно подключается в данном случае?

а) код Typescript из папки \src\packages\gdmn-db\src
б) код Javascript + .d.ts из папки \src\packages\gdmn-orm\node_modules\gdmn-db
в) код Javascript + .d.ts из папки \src\packages\gdmn-db\dist

Если один из последних двух пунктов, то кто и в какой момент компилирует код Typescript в Javascript? А если п. б) то еще и переносит измененные файлы из папки dist, куда их помещает компилятор typescript в папку node_modules?

Или по другому: если в одном окне редактора у меня открыт файл с классом из проекта gdmn-db, а во втором -- файл из gdmn-orm, который использует этот класс. Я делаю изменения в gdmn-db. В какой момент они станут известны в gdmn-orm?

а) сразу, без сохранения файла (как сейчас происходит при работе в рамках одного проекта). 
б) после того как я сохраню изменения gdmn-db на диске.
в) после сохранения изменений на диске и выполнения некоторых команд в терминале.

### свои скрипты для каждого проекта

Останется ли возможность выполнять команды tsc, npm run build, npm t для каждого проекта в отдельности? 

Например, выполнить npm run build внутри папки gdmn-front чтобы получить готовые к размещению на вебсервере файлы.

### сторонняя разработка отдельной библиотеки

Насколько я понимаю, теперь все исходники будут находиться в одном гигантском репозитории и если появится сторонний разработчик, который захочет присоединиться, например, к проекту gdmn-nlp, то ему всё равно придется качать все исходники и устанавливать **ВСЕ** библиотеки для всех проектов?

Если же мы хотим иметь отдельный репозиторий для gdmn-nlp, то только на таких условиях:

1. Текущая разработка и актуальные исходники в общем моно-репозитории gdmn. Отсюда идет публикация библиотеки на сайт npm.
2. Отдельный репозиторий для проекта gdmn-nlp и отдельная папка на диске, куда изменения из папки моно-репозитория переносятся вручную, сравнением и копированием измененных файлов. 
3. Сторонний разработчик, которому не нужны все исходники gdmn, может присоединиться только к проекту gdmn-nlp. В этом случае его изменения (pull request) поступают в отдельную папку, откуда вручную переносятся (копируются) в папку в рамках моно-репозитория и затем повторно комитятся уже в наш общий проект.

Существуют ли еще решения? 

(Про сабмодули я читал, что у них много существенных ограничений, из-за которых они не подойдут нам. Например, сабмодули могут существовать только внутри ветки мастер и т.п.)

**Comment by gsbelarus** [comment]
вопрос: обязательно ли публиковать библиотеки на сайте npm, чтобы использовать их в lerna?

**Comment by punkusha** [comment]
> вопрос: обязательно ли публиковать библиотеки на сайте npm, чтобы использовать их в lerna?

конечно, не обязательно. обязательно чтобы модуль являлся node.js package-м  (имел package.json с именем и версией).

**Comment by punkusha** [comment]
> Останется ли возможность выполнять команды tsc, npm run build, npm t для каждого проекта в отдельности?

не понимаю почему скрипты могут перестать работать. но куда интереснее, что lerna позволяет выполнить их сразу для всех репо или некоторого скоупа [lerna run](https://github.com/lerna/lerna/tree/master/commands/run)

**Comment by punkusha** [comment]
> сабмодули могут существовать только внутри ветки мастер
не верно. в дремучие времена может так и было, но сейчас ограничений нет (указывается любая ветка для ссылки на сабмодуль)

**Comment by punkusha** [comment]
> Существуют ли еще решения?

без сабмодулей кроме как копированием никак не получится - чисто code mirror даже без истории коммитов. не думаю, что в таком решении сейчас вообще есть смыл...

**Comment by punkusha** [comment]
на мой вгляд, gdmn-front и gdmn-back в моно-репозитории вообще не место. это для связанных либ... иначе тут вообще все в месс превратится и node_modules репозитория будет весить гигабайты. а также настанет момент когда фронт и бек вы захотите вынести из open-source.

если тут будут только либы, то особой нужды в зеркалах для комьюнити не будет. посмотрите на другие моно-репы, все нормально живут.

**Comment by gsbelarus** [comment]
нет. все объединим в один репозиторий. я уже устал по пол дня за каждым перепроверять каждую библиотеку. и еще, весь наш код, все библиотеки будут использовать **одну версию** сторонней библиотеки, а не так как сейчас.

**Comment by gsbelarus** [comment]
мы не одиноки, надо смотреть что используют другие:

https://github.com/lerna/lerna/issues/414

**Comment by punkusha** [comment]
а какие для нас преимущества git subtree перед git submodules? пока что выглядит намного сложнее

**Comment by gsbelarus** [comment]
![image](https://user-images.githubusercontent.com/5175764/47357751-573da700-d6d0-11e8-8e79-678516f773d1.png)

**Comment by punkusha** [comment]
если мы в моно репе будем юзать общие конфиги и скрипты, то имеет смысл юзать git subtree чтобы иметь чутка разные версии для комьюнити и моно

**Comment by sywka** [comment]
### Резюме:

> Предположим, что gdmn-orm использует gdmn-db. Т.е. содержит операторы import { something } from 'gdmn-db'; Что именно подключается в данном случае?

Будет использоваться код Javascript + .d.ts из папки `\node_modules\gdmn-db\dist`. Папка `\node_modules\gdmn-db` является symlink на сам пакет `\packages\gdmn-db`. Соответственно изменения в коде будут видны после компиляции исходников на typescript в javascript.
Компиляция может быть выполнена:
* в ручном режиме, вызовом команды `tsc`
* в автоматическом режиме, через watcher, который будет вызывать `tsc`, т.е. сохраняем файл и он сам компилируется
* средствами среды разработки, по сути тоже самое что и предыдущий пункт, только без конфигурации watcher

Где-то читал про возможность подключать typescript код напрямую через ts references, но это не точно

> Останется ли возможность выполнять команды tsc, npm run build, npm t для каждого проекта в отдельности?

Останется. Также появится возможность выполнять все одноименные скрипты разом для всех пакетов. Делается это вызовом `lerna run ${name}`, что равносильно вызову `yarn run ${name}` для каждого пакета

> Обязательно ли публиковать библиотеки на сайте npm, чтобы использовать их в lerna?

Нет. Обязательно чтобы модуль являлся node.js package-м (имел package.json с именем и версией)

> Существуют ли решения для разработки пакета как отдельной библиотеки в отдельном репозитории?

* submodules - но пока их подружить с lerna не вышло. Если конкретно, то не создается sumlink на пакет submodule
* git subtree - не совсем понимаю преимуществ над submodules

**Comment by sywka** [comment]
Есть еще [такая штука](https://github.com/splitsh/lite), как я понял lerna ее рекомендует, [все что нам нужно вроде есть](https://www.dotconferences.com/2016/05/fabien-potencier-monolithic-repositories-vs-many-repositories)
