### ISSUE TITLE
Имена файлов и папок

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#60]
Совершенно неудобно, когда куча файлов имеют одинаковые имена -- container.ts. И в интерфейсе редактора, и в сообщениях об ошибках на экране приходится вчитываться, искать глазами путь, чтобы понять о чем идет речь.

![image](https://user-images.githubusercontent.com/5175764/50372782-e3dbe700-05e5-11e9-917a-a95baebaccee.png)

Гораздо проще, когда сразу из имени файла все понятно -- ERModelContainer.ts.

Я уже переименовывал один раз и не понимаю зачем было переименовывать обратно.

**Comment by punkusha** [comment]
потому что надо придерживаться единого стиля хотябы в своем package. не нравится - переименовывайте во всех scene-модулях
