### ISSUE TITLE
Ошибка при выполнении тестов с базой данных

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#61]
Периодически при выполнении `yarn test` в корне получается такая ошибка:

![image](https://user-images.githubusercontent.com/5175764/50375080-06332c00-0609-11e9-8ab0-d45a91bb6f8f.png)

При повторном выполнении -- все тесты проходят нормально.

Может ли это быть связано с параллельным выполнением тестов? Попыткой одновременного обращения к одной и той же бд?

**Comment by sywka** [comment]
См #74
