### ISSUE TITLE
Что-то не так с автоматической проверкой

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#62]
Перед комитом у себя выполнил: yarn, yarn rebuild, yarn test. Все прошло без запинки, а в гите такая картина:
![image](https://user-images.githubusercontent.com/5175764/50385413-43b9b700-06e6-11e9-9e23-fa598407ae7e.png)

**Comment by sywka** [comment]
Когда перенастраивал на pipeline забыл добавить очередь билдов. Сейчас должно работать правильно
