### ISSUE TITLE
Кэширование конекта к БД и считанной ER модели

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#66]
Так полжизни можно потратить на отладку. Почему после каждого изменения во фронте и его перезагрузке в браузере начинается полное перечитывание структуры БД?

Обсуждалось, что при подключении первого клиента создается DBConnection, объект внутри которого считывается и хранится ER Model. 

Для каждого сетевого клиента внутри DBConnection создается Session.

Даже после закрытия последней сессии DBCOnnection еще какое-то время остается загруженным и ждет очередного подключения.

**Comment by sywka** [comment]
Обсуждалось как раз то, что нет смысла делать для такого случая дополнительный timeout, это нужно только для тестирования и может быть имитировано при помощи одной открытой сессии.
Для этого можно:
* либо открыть одну дополнительную вкладку в браузере, авторизоваться и держать ее всегда открытой;
* либо открыть вкладку, авторизоваться и закрыть ее (принудительный разрыв соединения включит timeout на самой сессии и она будет висеть сутки, а соответственно и Application с кэшированной ERModel будет висеть столько же)

**Comment by gsbelarus** [comment]
Так и в реальной жизни такое может понадобиться. Например на небольшом предприятии, где может быть ситуация один залогинился, поработал, вышел. Через 5 минут второй логинится и... ждет загрузки всего.

**Comment by sywka** [comment]
На небольшом предприятие с одним компьютером на весь персонал не будет базы в 100Гб) и если такой сценарий использования и произойдет, пользоваться системой он сможет через несколько секунд. 
На большом предприятии никто с личного компьютера вылогиниваться не будет.
В любом случае если нужно - добавим, просто не хотелось сейчас на это время тратить

**Comment by gsbelarus** [comment]
Скорость загрузки модели зависит не от размера БД, а от количества таблиц и т.п. Так что и намалой базе и на большой она будет одинакова. Если там буду загружены те же прикладные решения. Так что надо делать.
