### ISSUE TITLE
Подключение к разным бд

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#69]
Надо предусмотреть параметры в команде yarn start в папке gdmn-back, чтобы в офисе я мог подключаться к одной бд, а дома к другой, которая лежит у меня локально на компе.

**Comment by sywka** [comment]
На стороне back уже реализовано подключение к разным базам в контексте пользователя. Осталось добавить возможность подключения к разным базам на стороне front.

Т.е пользователь введя данные для авторизации подключается к базе авторизации и видит список баз данных. Он может добавлять/удалять бд и подключаться к ним. После подключения к одной из баз, интерфейс переходит в режим коннекта с этой базой и дальше работа происходит в этой базе. Так же он может закрыть коннект с этой бд и попав на экран со списком баз подключиться к другой. Авторизация происходит через главную бд авторизации. В будущем можно добавить авторизацию на каждой из баз.
