### ISSUE TITLE
Использование только части таблиц сущности в запросе

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#71]
Наш классический пример -- Сущность Компания. Данные, находятся в трех таблицах, из которых две обязательные GD_CONTACT, GD_COMPANY и одна weak relation GD_COMPANYCODE.

Запрос на извлечение данных сущности должен выглядеть следующим образом:

```
  ...
  GD_CONTACT JOIN GD_COMPANY
    LEFT JOIN GD_COMPANYCODE
  ...
```

Вопрос в том, если эта сущность является атрибутом другой сущности и пользователь задал условие отбора по одному атрибуту компании. Например, в документе Накладная атрибут Поставщик типа Компания. Пользователь хочет отобрать только те накладные, у которых в полном названии поставщика присутствует аббревиатура "ОАО".

С точки зрения оптимизации логично в итоговый запрос добавлять только те таблицы из сущности Компания, поля которых задействованы в условиях выборки или выбраны пользователем для отображения.

Т.е. в данном примере только таблица GD_COMPANY должна попасть в итоговый запрос:

```
  ...
  GD_DOCUMENT d
    JOIN GD_COMPANY co ON co.contactkey = d.supplierkey
  ...
  WHERE
    co.FULLNAME LIKE '%ОАО%'
```

JOIN или LEFT JOIN в данном случае зависит от того атрибут обязательный или нет.

**Comment by sywka** [comment]
Для случая который вы описали оно будет работать правильно, но в случае прямого запроса к entity Company и отбора по полю находящемуся в таблице GD_CONTACT таблица GD_COMANY присоединена не будет.

FROM GD_CONTACT JOIN GD_COMPANY
    LEFT JOIN GD_COMPANYCODE
  ...
в этом случае он получит все записи из GD_CONTACT с contacttype = компания, даже те которых нет в GD_COMPANY (вы говорили такое возможно).
Если после этого в этом же запросе пользователь запросит дополнительное поле из GD_COMPANY, она присоединится через JOIN и получится не состыковка результатов, т.к во втором случае отсекутся отсутствующие записи в GD_COMPANY. 
Поэтому я предлагал делать для таких случаев LEFT JOIN, либо присоединения всех таблиц одной entity, без оптимизации.

**Comment by sywka** [comment]
Решение: Оставляем присоединение таблиц Entity первого уровня (т.е из первой link внутри EntityQuery) без оптимизации. Присоединение таблиц через ссылку из атрибута происходит с применением оптимизации.
