### ISSUE TITLE
 There is error on screen on our server right now

### ISSUE THREAD

**Issue by sywka** [gsbelarus/gdmn#73]
![image](https://user-images.githubusercontent.com/3028102/50562085-ed6df900-0d21-11e9-8b43-51f708d9ed4d.png)

**Comment by sywka** [comment]
Обычная ошибка таймаута, видимо очень большое количество итераций поставили, а тайм-аут не подняли

**Comment by gsbelarus** [comment]
а как и где его поднять?

**Comment by sywka** [comment]
https://github.com/gsbelarus/gdmn/blob/master/packages/gdmn-db/test/fb.test.ts#L165

**Comment by sywka** [comment]
Хотя странно что именно этот тест с таймаутом свалился
