### ISSUE TITLE
Тесты на параллельные запросы к БД

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#76]
Запрос к БД идет параллельно? Не блокирует петлю nodejs?

Надо сделать тест, когда по сети идет подключение к бэку, затем на бэк посылается N запросов. Каждый запрос должен выполняться в своей транзакции. Запросы должны быть достаточно длительными (секунды, десятки секунд) для того, чтобы все N запросов успели отправиться на сервер еще до того, как он обработает и вернет самый первый из них.

Цель теста -- проверить чтобы петля сообщения нода продолжала работать пока Firebird обрабатывает SQL запрос.

**Comment by sywka** [comment]
Стресс тесты в **gdmn-db** построены так, что все запросы в контексте одного теста выполняются сразу, не дожидаясь выполнения каждого. Правда каждый из трех тестов выполняется на своей одной транзакции. Для **gdmn-back** тестов вообще нет.
