### ISSUE TITLE
Повторяемый случай падения бэка

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#81]
1. Взять исходники из комита a3d6fd66f8527647e6e566c642c187b92147ddab.
2. Запустить бэк и фронт.
3. Во фронте открыть ER Model, выбрать Company и открыть ее на просмотр.

Бэк упадет. Там во фронте есть ошибка, но не в этом дело. Главное что это 100% воспроизводимый случай падения бэка. Надо всё-таки разобраться. Например, поставить в самом низу логирование всех SQL идущих на сервер и запись их перед отправкой в файл. Потом попробовать проиграть полученную последовательность. Если она будет приводить к ошибке, то сделать маленькую программку для воспроизведения и отослать автору для исправления драйвера.

Если отдельное проигрывание не будет давать ошибки, то дело в нашем коде. Надо внимательно посмотреть. Может есть непонимание работы observables (которые работают не так как ивенты) или чего то еще.

И еще, пожалуйста, кода думаете о коде, думайте не только о том, что на вход придут правильные сообщения в правильном порядке с правильными данными, но и абсолютная ерунда в случайном порядке. Но, это никак не должно валить сервер.

**Comment by gsbelarus** [comment]
Да, в этот лог надо всё включить. и коннекты/ дисконнекты и старты/коммиты транзакций.

**Comment by sywka** [comment]
Так уже определили на простом тесте, с большим количеством итераций. Сейчас разбираюсь

**Comment by sywka** [comment]
См #74
