### ISSUE TITLE
Преобразование BLOB на сервере при загрузке ER Model

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#86]
Сначала выполнять запрос, который вернет максимальные длины для всех строковых блобов:

```sql
SELECT
  ...
  MAX(CHARACTER_LEGHTH(rsb$default_source)),
  ...
```

Потом уже использовать их в запросе для преобразования БЛОБа в строку:

```sql
  SELECT
    CASE(rdb$default_source AS VARCHAR(37))
    ...
```

**Comment by sywka** [comment]
После проверки, выяснилось, что это не дает прироста производительности
