### ISSUE TITLE
Общая глобальная транзакция на чтение

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#90]
Старт-коммит транзакции дорогостоящий процесс. Например, в тесте на отправку и выполнение параллельных запросов на сервер бд, если все запросы выполняются на одной, заранее открытой, транзакции, то удается выполнить 160-165 запросов в секунду. Но, если для каждого запроса стартовать свою транзакцию и комитить ее после его выполнения, то скорость падает до 70-75 запросов в секунду.

В Гедымине у нас есть глобальная **read only**, **read comitted**, **rec version** транзакция и запросы на чтение выполняются на ней, а отдельные короткоживущие транзакции открываются только когда меняются данные и сразу же комитятся по завершении операции обновления.

Надо и в #gdmn предусмотреть такую же глобальную транзакцию, которая будет открываться  сразу после установки соединения (или лучше по первому требованию) и закрываться перед закрытием соединения к БД. И, соответственно, в **IQuery** мы должны иметь возможность указать или использовать общую транзакцию, или открывать свою, или использовать некоторую третью, которой программист сам управляет.

**Comment by sywka** [comment]
Внутри класса `AConnection` модуля **gdmn-orm** теперь есть объект 
```ts
...
protected _readTransaction?: ATransaction;
...
```

Создание транзакции происходит при создании соединения с флагом `readTransaction: boolean`, сама транзакция доступна через getter. Если соединения создается без флага, getter кидает ошибку.
Параметры создания транзакции:
```ts
{
  isolation: Isolation.READ_COMMITED,
  accessMode: AccessMode.READ_ONLY
}
```
