### ISSUE TITLE
Откуда может брать старый путь к БД?

### ISSUE THREAD

**Issue by sunnycreature** [gsbelarus/gdmn#94]
в testConfig.json прописан правильный путь, но когда фронт пытается к бэку подключиться, бэк кидает такую ошибку:

![image](https://user-images.githubusercontent.com/12336960/52324689-561c5580-29f3-11e9-9b34-27da470f7086.png)

т.е. где-то у него прописан старый путь к бд. где?

**Comment by sunnycreature** [comment]
Похоже, что что-то намертво прописывается в main.fdb и как его потом оттуда выдрать? и поменять?

**Comment by sywka** [comment]
Да, так и есть. Этот конфиг сделан для тестов и при создании пользователя записывает эти данные в базу авторизации. На данный момент обойти это можно только ручным изменением данных в БД или удалением БД авторизации
