### ISSUE TITLE
Тестовый gdmn-nlp-back для gdmn-nlp-demo

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#95]
Для gdmn-nlp-demo мне надо простые REST поинты для доступа к бэку. Проект демонстрационный, не промышленный, поэтому я не хочу усложняться аутентификацией, тасками, протоколом обмена и т.п.

Всё что мне надо:

1. Возможность получить сериализованную ERModel
2. Возможность послать IQuery и получить ответ в виде сериализованных данных RecordSet.

**Comment by sywka** [comment]
Т.е нужно просто выдрать из бэка два куска (считывание ermodel и выполнение результата query) и оформить как отдельный сервер?
Как быть с икрементной подгрузкой для больших объемов данных? Когда нужен готовый сервер?

**Comment by gsbelarus** [comment]
инкрементная не нужна. запрос -- ответ.

а зачем выдирать. просто бэк дор в действующем сервере сделать. 2  rest
point.

чц, 7 лют 2019, 14:43: карыстальнік Lomashko Yuri <notifications@github.com>
напісаў:

**Comment by sywka** [comment]
После добавления кластеризации проще отдельный сервер собрать

**Comment by sywka** [comment]
## Enpoints
| Request | Response |
| --- | --- |
| **GET** `/ermodel` | 200: Успешно, `body: IERModel`;<br>500: Внутренние ошибки, `body: Error`; |
| **GET** `/data?query=query` | 200: Успешно, `body: IEntityQueryResponse`;<br>400: Некорректный запрос, `body: Error`;<br>500: Ошибка выполнения sql и другие внутренние ошибки, `body: Error`; |

### Encode query:
```ts
import {EntityQuery} from "gdmn-orm";

let entityQuery: EntityQuery;
...
const query = encodeURIComponent(entityQuery.serialize());
...
```
### Decode query:
```ts
import {EntityQuery} from "gdmn-orm";

let query: string;
...
const entityQuery = EntityQuery.deserialize(erModel, decodeURIComponent(query));
...
```
